import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import { Abbreviation } from './Abbreviation';

describe('Abbreviation', () => {
  it('renders an abbr element with the correct text', () => {
    render(<Abbreviation title="HyperText Markup Language">HTML</Abbreviation>);

    const element = screen.getByText('HTML');
    expect(element.tagName).toBe('ABBR');
  });

  it('renders with the correct title attribute', () => {
    render(<Abbreviation title="HyperText Markup Language">HTML</Abbreviation>);

    const element = screen.getByText('HTML');
    expect(element).toHaveAttribute('title', 'HyperText Markup Language');
  });

  it('applies the default variant style', () => {
    render(<Abbreviation title="HTML">HTML</Abbreviation>);

    const element = screen.getByText('HTML');
    // Matches the hashed class name generated by vanilla-extract
    expect(element.className).toMatch(/abbreviationStyle/);
  });

  it('applies the noUnderline variant style', () => {
    render(
      <Abbreviation title="HTML" variant="noUnderline">
        HTML
      </Abbreviation>
    );

    const element = screen.getByText('HTML');
    expect(element.className).toMatch(/noUnderline/);
  });

  it('applies custom class names', () => {
    render(
      <Abbreviation title="HTML" className="custom-class">
        HTML
      </Abbreviation>
    );
    const element = screen.getByText('HTML');
    expect(element).toHaveClass('custom-class');
  });

  it('forwards additional props to the root element', () => {
    render(
      <Abbreviation title="HTML" data-testid="abbr-test">
        HTML
      </Abbreviation>
    );
    expect(screen.getByTestId('abbr-test')).toBeInTheDocument();
  });

  it('forwards the ref to the abbr element', () => {
    const ref = { current: null as HTMLElement | null };
    render(
      <Abbreviation
        title="HTML"
        ref={(node) => {
          ref.current = node as HTMLElement | null;
        }}
      >
        HTML
      </Abbreviation>
    );
    expect(ref.current).toBeInstanceOf(HTMLElement);
    expect(ref.current?.tagName).toBe('ABBR');
  });
});
